name: Build and Release Android Apk

on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
      - '*.x' # maintenance releases branches

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
